const USER_COLLECTION = 'user';
const FUNCTION_COLLECTION = 'function';
const POST_COLLECTION = 'post';
const ROLE_COLLECTION = 'role';
const TRACKING_COLLECTION = 'tracking';
const CUSTOMER_COLLECTION = 'customer';
const CAMPAIGN_COLLECTION = 'campaign';
const CAR_GROUP_COLLECTION = 'car_group';
const CAR_COLLECTION = 'car';
const DRIVER_COLLECTION = 'driver';
const AREA_COLLECTION = 'area';
const LOG_COLLECTION = 'log';
const CONFIRM_CAR_STATUS_COLLECTION = 'confirm_car_status';
const FEEDBACK = 'report';
const HOME_CALCULATOR_COLLECTION = 'home_calculator_km_before';

const TEST_COLLECTION = 'test111';
module.exports = {
  USER_COLLECTION,
  FUNCTION_COLLECTION,
  POST_COLLECTION,
  ROLE_COLLECTION,
  TRACKING_COLLECTION,
  CUSTOMER_COLLECTION,
  CAMPAIGN_COLLECTION,
  CAR_GROUP_COLLECTION,
  CAR_COLLECTION,
  DRIVER_COLLECTION,
  AREA_COLLECTION,
  LOG_COLLECTION,
  CONFIRM_CAR_STATUS_COLLECTION,
  FEEDBACK,
  HOME_CALCULATOR_COLLECTION,
  
  TEST_COLLECTION
};
